// src/react/apps/Nav.tsx
import React from 'react'
import { Iframe, Provider, useIframeContext } from '@unionavatars/iframe/react'

function NavBar () {
  const { eventer } = useIframeContext()
  const goto = (page: string) => {
    eventer?.request('goto', page)
  }
  return (
    <aside>
      <header>Go to:</header>
      <ul>
        <li><button onClick={() => goto('Login')}>Login</button></li>
        <li><button onClick={() => goto('Register')}>Register</button></li>
        <li><button onClick={() => goto('RecoverPassword')}>Recover Password</button></li>
      </ul>
    </aside>
  )
}

export default function Nav () {
  return (
    <Provider>
      <article>
        <NavBar />
        <section>
          <Iframe src="http://iframe.unionavatars.com" />
        </section>
      </article>
    </Provider>
  )
}

// src/vue/apps/Nav.tsx
/* eslint-disable react-hooks/rules-of-hooks */
import { defineComponent, h } from 'vue';
import { Iframe, useIframeContext } from '@unionavatars/iframe/vue' 

const NavBar = defineComponent({
  setup () {
    const ctx = useIframeContext()
    const goto = (page: string) => {
      ctx?.eventer?.request('goto', page)
    }
    return () => (
      h('aside', [
        h('header', 'Go to:'),
        h('ul', [
          h('li', h('button', { onClick: () => goto('Login') }, 'Login')),
          h('li', h('button', { onClick: () => goto('Register') }, 'Register')),
          h('li', h('button', { onClick: () => goto('RecoverPassword') }, 'Recover Password'))
        ])
      ])
    )
  }
})

const Nav = defineComponent({
  setup () {
    return () => (
      h('article', [
        h(NavBar),
        h('section', [
          h(Iframe, { src: 'http://iframe.unionavatars.com' })
        ])
      ])
    )
  }
})
export default Nav
